app/models.py
from . import db
from werkzeug.security import generate_password_hash,check_password_hash
from flask_login import UserMixin
from . import login_manager
from datetime import datetime

@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))

class User(UserMixin,db.Model):
    __tablename__ = 'users'
    id = db.Column(db.Integer,primary_key = True)
    username = db.Column(db.String(255))
    email = db.Column(db.String(255),unique = True,index = True)
    role_id = db.Column(db.Integer,db.ForeignKey('roles.id'))
    bio = db.Column(db.String(255))
    profile_pic_path = db.Column(db.String())
    pass_secure = db.Column(db.String(255))

    @property
    def password(self):
        raise AttributeError('You cannot read the password attribute')

    @password.setter
    def password(self, password):
        self.pass_secure = generate_password_hash(password)


    def verify_password(self,password):
        return generate_password_hash(password)

    def __repr__(self):
        return f'User {self.username}'

class Role(db.Model):
    __tablename__ = 'roles'

    id = db.Column(db.Integer,primary_key = True)
    name = db.Column(db.String(255))
    users = db.relationship('User',backref = 'role',lazy="dynamic")

    def __repr__(self):
        return f'User {self.name}'

class Pitch(db.Model):
    __tablename__ = 'pitches'
    id = db.Column(db.Integer, primary_key=True)
    pitch_title = db.Column(db.String)
    pitch_content = db.Column(db.String(800))
    category = db.Column(db.String)
    posted = db.Column(db.DateTime, default=datetime.utcnow)
    user_id = db.Column(db.Integer, db.ForeignKey("users.id"))
    likes = db.Column(db.Integer)
    dislikes = db.Column(db.Integer)
    comments = db.relationship('Comment', backref='pitch_id', lazy="dynamic")

    def save_pitch(self):
        db.session.add(self)
        db.session.commit()
    @classmethod
    def get_pitches(cls, category):
        pitches = Pitch.query.filter_by(category=category).all()
        return pitches
    @classmethod
    def get_pitch(cls, id):
        pitch = Pitch.query.filter_by(id=id).first()
        return pitch
    @classmethod
    def count_pitches(cls, uname):
        user = User.query.filter_by(username=uname).first()
        pitches = Pitch.query.filter_by(user_id=user.id).all()
        pitches_count = 0
        for pitch in pitches:
            pitches_count += 1
        return pitches_count
    @classmethod
    def all_pitches(cls):
        pitches = Pitch.query.all()

        return pitches 
        
        
class Comment(db.Model):
    __tablename__ = 'comments'
    id = db.Column(db.Integer, primary_key=True)
    comment = db.Column(db.String(800))
    user_id = db.Column(db.Integer, db.ForeignKey("users.id"))
    pitch = db.Column(db.Integer, db.ForeignKey("pitches.id"))
    def save_comment(self):
        db.session.add(self)
        db.session.commit()
    @classmethod
    def get_comments(cls, pitch):
        comments = Comment.query.filter_by(pitch_id=pitch).all()
        return comments

app/main/forms.py
from flask_wtf import FlaskForm
from wtforms import TextAreaField,SubmitField,StringField
from wtforms.validators import Required

class PitchForm(FlaskForm):
    title = StringField('Pitch title',validators=[Required()])
    pitch = TextAreaField('Pitch ', validators=[Required()])
    category = StringField( 'Category', validators=[Required()])
    submit = SubmitField('Submit')

class UpdateProfile(FlaskForm):
    bio = TextAreaField('Tell us about you.',validators = [Required()])
    submit = SubmitField('Submit')

app/__init__.py
from flask import Flask
from flask_bootstrap import Bootstrap
from .config import config_options
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager

login_manager = LoginManager()
login_manager.session_protection = 'strong'
login_manager.login_view = 'auth.login'

bootstrap = Bootstrap()
db = SQLAlchemy()

def create_app(config_name):
    app = Flask(__name__)
    # Creating the app configurations
    app.config.from_object(config_options[config_name])
    
    # Initializing flask extensions
    db.init_app(app)
    login_manager.init_app(app)
    bootstrap.init_app(app)
    
    # Registering the blueprint
    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)
    from .auth import auth as auth_blueprint
    app.register_blueprint(auth_blueprint,url_prefix = '/auth')
    
    return app

app/main/__init__.py
from flask import Blueprint
main = Blueprint('main',__name__)
from . import views,error

def create_app(config_name):
    app = Flask(__name__)

    # Creating the app configurations
    app.config.from_object(config_options[config_name])

    # Initializing flask extensions
    bootstrap.init_app(app)

    

    return app

app/main/views.py
from flask import render_template,redirect,url_for,abort
from . import main
from ..models import User,Pitch
from .forms import UpdateProfile,PitchForm
from .. import db
from django.contrib.auth.decorators import login_required

# Views
@main.route('/')
def index():
    pitches = Pitch.all_pitches()
    title = 'Pitch - Pitch Website'
    return render_template('index.html',title = title, pitches = pitches)

@main.route('/pitch/<pitch_id>')
def pitch (pitch_id):
    
    return render_template('pitch.html', id = pitch_id)

@main.route('/user/<uname>')
def profile(uname):
    user = User.query.filter_by(username = uname).first()

    if user is None:
        abort(404)

    return render_template("profile/profile.html", user = user)

@main.route('/user/<uname>/update',methods = ['GET','POST'])
@login_required
def update_profile(uname):
    user = User.query.filter_by(username = uname).first()
    if user is None:
        abort(404)

    form = UpdateProfile()

    if form.validate_on_submit():
        user.bio = form.bio.data

        db.session.add(user)
        db.session.commit()

        return redirect(url_for('.profile',uname=user.username))

    return render_template('profile/update.html',form =form)

@main.route('/pitch/new/',methods = ['GET','POST'])
@login_required
def  new_pitch():
    form = PitchForm()
    if form.validate_on_submit():
        title = form.title.data
        pitch = form.pitch.data
        category = form.category.data
        
        new_pitch = Pitch(pitch_title=title, pitch_content=pitch,
                          category=category, user=current_user, likes=0, dislikes=0)

        # Save pitch method
        new_pitch.save_pitch()
        return redirect(url_for('.index'))

    title = 'New pitch'
    return render_template('new_pitch.html', title=title, form = form)

app/templates/base.html
{% extends 'bootstrap/base.html'%}


<head>
    <meta charset="utf-8"> {% if title %}
    <title> {{ title }}</title>
    {% else %}
    <title> Welcome to the best Pitching website </title>
    {% endif %}
</head>

<body>
    <!-- Navbar block  -->
    {% block navbar %} {% include 'navbar.html' %} {% endblock %}

</body>

</html>

app/templates/fourOwfour.html
{% extends 'base.html'%}
<!-- Styles block -->

{% block styles%} {{ super() }}
<link rel="stylesheet" href="{{url_for('static',filename='css/error.css')}}"> {% endblock %} {% block content %}

<body style="background-image: url(https://cdn.mos.cms.futurecdn.net/PuXipAW3AXUzUJ4uYyxPKC-1200-80.jpg);">
    <div class="container-fluid">

    </div>
</body>
{% endblock %}

app/templates/index.html
{% extends 'base.html'%}
<!-- Styles block -->

{% block styles%} {{ super() }}
<link rel="stylesheet" href="{{url_for('static',filename='css/index.css')}}"> {% endblock %}
<!-- Content block -->
<html>

<head>
    <meta charset="utf-8"> {% if title %}
    <title> {{ title }}</title>
    {% else %}
    <title> Welcome to the best Pitching website </title>
    {% endif %}
</head>

<body>
    {% block content %} {% for pitch in pitches %}
    <div class="card" style="width: 18rem;">
        <div class="card-body">
            <h5 class="card-title">{{Pitch.pitch_content}}</h5>
            <p class="card-text">With supporting text below as a natural lead-in to additional content.</p>
            <a href="#" class="btn btn-primary">Go somewhere</a>
        </div>
    </div>
    {% endfor %} {% endblock %}
</body>

</html>

app/templates/navbar.html
<div class="navbar navbar-inverse" role="navigation">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/"> Pitch </a>
        </div>
        <div class="navbar-collapse collapse">

            <ul class="nav navbar-nav">
                <li><a href="/">Home</a></li>
            </ul>
        </div>
        <ul class="nav navbar-nav navbar-right">
            {% if current_user.is_authenticated %}
            <li><a href="{{url_for('main.profile',uname=current_user.username)}}">Profile</a></li>
            <li style="color:white;padding:15px;">{{current_user.username}}</li>
            <li><a href="{{url_for('auth.logout')}}">Sign out</a></li>
            {% else %}
            <li><a href="{{url_for('auth.login')}}">Sign in</a></li>
            {%endif%}
        </ul>

    </div>
</div>

app/templates/new_pitch.html
{% extends 'base.html'%} {% import "bootstrap/wtf.html" as wtf %} {% block content %}

<div class="container">
    <div class="col-md-12">
        <h3>Create a pitch</h3>
        <hr> {{ wtf.quick_form(form) }}
    </div>

</div>

{% endblock %}

app/templates/profile/profile.html
{% extends 'base.html'%} {% block content %} {% if user == current_user %}
<a href="{{url_for('main.update_profile',uname=user.username)}}">Edit profile</a> {% endif %}
<div class="container">
    <div class="row">
        <!-- displaying  Username-->
        <div class="col-md-4">
            <h3> {{user.username| capitalize}} </h3>

            <!--Displaying user bio-->
            {% if user.bio %}
            <p> {{user.bio}}</p>
            {%else%}
            <p> {{user.username| capitalize}} has no bio </p>
            {% endif %}
        </div>

        <!--Display profile photo-->
        <div class="col-md-4">

            {% if user.profile_pic_path %}
            <img src="{{url_for('static',filename=user.profile_pic_path)}}" alt="" class="img-thumbnail"> {%else%}
            <p>No profile picture</p>
            {% endif %}
        </div>
    </div>
</div>
{% endblock %}

app/templates/profile/update.html
{% extends 'base.html' %} {% import 'bootstrap/wtf.html' as wtf %} {% block content %}
<div class="container">
    {{wtf.quick_form(form)}}
</div>
{% endblock %}